spring:
  application:
    name: UserAuthentication

  datasource:
    url: jdbc:mysql://localhost:3306/guava_security
    username: dev
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  #here i am specifying that i want to create-drop the database every time i start the application (another good option is update)

    hibernate.ddl-auto: create-drop
