

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"

  cloud:
    gateway:
      routes:
        - id: department-service
          uri: http://localhost:8081
          predicates:
            - Path=/department/**




logging:
  level:
    org.springframework.cloud.gateway: DEBUG

